# Generated by Django 2.0.6 on 2019-07-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assemblies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.CharField(max_length=20)),
                ('assembly_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_ident', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=50)),
                ('district_logo', models.CharField(max_length=1000)),
                ('district_pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='public_complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=20)),
                ('complaint_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('complaint_photo', models.ImageField(upload_to='static/images/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andhrapradesh.assemblies')),
            ],
        ),
        migrations.AddField(
            model_name='assemblies',
            name='districts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andhrapradesh.district'),
        ),
    ]
