# Generated by Django 2.0.6 on 2019-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andhrapradesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='public_complaints',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='public_complaints',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='public_complaints',
            name='complaint_photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='public_complaints',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
