# Generated by Django 2.0.6 on 2019-07-19 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andhrapradesh', '0002_auto_20190719_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_complaints',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_complain', to=settings.AUTH_USER_MODEL),
        ),
    ]
